### ISSUE TITLE
 Hue bridges not loaded

### ISSUE THREAD

**Issue by ro8inmorgan** [elgatosf/streamdeck-philipshue#35] opened 2022-06-22 19:35 UTC
Only when I start Stream deck as administrator I see my hue bridges, but when stream deck auto starts with windows no bridges are being shown,. And even pairing again with the bridge won't save it.

**Comment by LeoMartinDev** [comment] 2022-09-12 09:32
Same, I have to re pair my bridge every time I restart my computer

**Comment by TheCompJock** [comment] 2022-09-17 03:45
Seems like a very common issue, reddit is full of people complaining about the same issues. When my stream deck forgets the hue hub and I scan for a hub, it fails in a micro second. When its working The option to add a hub has  a second sync page that tells you to start the sync but when its not working that screen never appears just an instant fail.  Other times it finds and pairs but the hub it just found is not available in the SD button drop down and i have to reboot the SD app. Ugh!

So A second option I found to use the stream deck with my Hue lights is to use the stream deck IFTTT plugin and webhooks. It seems to be much more stable and with a IFTTT pro account you can string together multiple actions with a single button trigger.  Use these instructions to setup the buttons to use web-hook triggers https://github.com/tobimori/streamdeck-ifttt. This is actually a very useful plugin because IFTTT allows you to control may other IOT devices & services with the stream deck.

**Comment by dkern** [comment] 2022-09-18 11:16
Do you have tried to install the current version out of this Repo manually? The version available in Stremdeck is very old. The current version here has some fixed regarding the bridges. Maybe that solves the issues.

**Comment by manuelgrabowski** [comment] 2022-09-24 12:48
I can successfully pair when entering my bridge IP manually in the plugin version from this repo, but afterwards the bridge still doesn't show up in the dropdown list.

**Comment by hacnic** [comment] 2022-10-06 11:43
Same probleme here, the bridge doesnt show up at all after successful pairing.

**Comment by spagettifritz** [comment] 2022-10-15 20:57
Same problem here.
Reinstalled Stream Deck application.
Uninstalled and cleaned everything of v1.4 of the Hue Plugin from the Stream Deck Store.
Installed v1.5 from Github
Manually adding the bridge via IP is successful
But the bridge is not listed in drop down.

**Comment by manuelgrabowski** [comment] 2022-10-16 19:53
I've opened a Support Request with Elgato for this now, ticket number 2005571769. I'd encourage you to do the same, feel free to reference the ticket number in your request. I don't think much will come from comments on these issues, they'll need to see support tickets resulting from this defect for resources to be allocated towards a fix.

**Comment by dkern** [comment] 2022-10-16 20:30
> I've opened a Support Request with Elgato for this now, ticket number 2005571769. I'd encourage you to do the same, feel free to reference the ticket number in your request. I don't think much will come from comments on these issues, they'll need to see support tickets resulting from this defect for resources to be allocated towards a fix.

I think you missed something. This is no official released software from Elgato. Maybe take a look to the readme:

> This sample plugin allows controlling Philips Hue lights in your network. It's a demonstration of the Stream Deck SDK.

So you asking for support for a sample/demo? 😉

**Comment by manuelgrabowski** [comment] 2022-10-16 20:58
I'm aware of the status of this repositry, which is exactly why I did what I described above. This plugin is also distributed via their official "App Store" in the Stream Deck app, and that version is broken in the same way – even more so, actually, because you can't even manually set the IP in the outdated build that is uploaded there. The version distributed there is with "by Elgato" and refers to https://help.elgato.com under "Support" directly on the page of that plugin:

![image](https://user-images.githubusercontent.com/13483728/196057896-5e8fd2ca-a9e7-45e0-87d5-320aea838ce8.png)


The ticket was already accepted as a valid request and is being investigated – how much that is actually worth I can't say yet, of course. I'm not sure why you'd think opening a ticket for this based on the above isn't the best step, though.

**Comment by dkern** [comment] 2022-10-16 21:13
Well, because the issue is known, and if you want support you may want to call Phillips. Because the real bug is caused by the meethue API, what it not a part of Elgato. The manual IP feature I added is just a workaround. And as the Devs are here directly on GitHub too, I really don't see a reason for a ticket, especially because it's a demo.

But thats just my point of view. We'll see what happens. :)

**Comment by manuelgrabowski** [comment] 2022-10-16 21:30
I did, and Philipps Hue Support of course simply redirect back to Elgato, mumbling some nonsense about possibly improper API usage. That is of course absolute nonsense as I can prove that the 429 response is coming regardless of the plugin being the client, but there's not much more I can do as an enduser. So I'll have to go to the provider of the broken functionality. Maybe Elgato can talk to Philips and get them to get their shit together – probably not, but a Support ticket is still the proper channel.

Take a step back and look at the above without your background knowledge as a developer. What would someone that doesn't know about Github, APIs, builds etcpp. do when they encounter this behavior? Contact Support via the listed avenue. The plugin in the "App Store" isn't called a demo. It's officially advertised functionality there. Maybe as a result of the ticket they'll just drop the plugin from the store, or add a disclaimer that it's indeed not officially supported and provided on a best-effort basis, or as a demo. That's fine too, still an improvement from the status quo.

**Comment by alfadormx** [comment] 2022-12-01 23:36
Hello everybody, 

I just commented on this issue here https://github.com/elgatosf/streamdeck-philipshue/issues/39#issuecomment-1334578907

As @dkern mentions, he already fixed the issue of trying to store the Bridge over and over again. However, his code fix was pushed into this repository AFTER v 1.5 was packaged. As a result, his fix is not included in what this repository considers to be the latest version. In other words, v 1.5 is flawed.

The fix is there just not published yet. You'll have to repackage and reinstall the plugin manually as per the comments listed in the other issue.

**Comment by alfadormx** [comment] 2022-12-01 23:56
Ok sorry for too many comments my friends.
If you will go create yourselves the package, do it  but by checking out commit 2bc1a1 (two commits before the latest one). The other commits above it are broken caused by a bad merge from a pull request that tries to fix some  translation issues.

![image](https://user-images.githubusercontent.com/5934048/205183742-e852b8e9-e3a9-4c57-96ad-5dc09ffbdb51.png)

In any case, I have created the package myself and tested it successfully. You can download it from here (just unzip and GO!)
[com.elgato.philips-hue.zip](https://github.com/elgatosf/streamdeck-philipshue/files/10137045/com.elgato.philips-hue.zip)

If you don't trust my file you can always download the code, checkout the right commit and package it. Otherwise, have fun!

**Comment by tiptronic** [comment] 2022-12-21 18:50
Hi friends,
in our quest to catch-up with your requests, I'm pushing a new version of the hue-plugin (1.6.2).
I merged all PRs where it made sense and fixed localization.
-
We also added support for the new Stream Deck + dial/panels.

Please note: the whole plugin was originally meant just as a sample, so it's not in perfect shape, but we'll dedicate a bit of time to it to improve.

If there are no major issues with the version just posted, we'll add it to the store.
For now, we're interested in collecting information about overall functionality. If that's stable, we'll work from there...

If you want to contribute or have something to add, please create an issue...

**Comment by manuelgrabowski** [comment] 2022-12-21 18:56
Thanks @tiptronic, much appreciated. I can confirm that what @alfadormx wrote above seems to be correct – ever since using that version, the issue has not yet re-appeared. I've only been using it for about a week, but in the past it would have been very unlikely to go a full week without running into the issue.

**Comment by manuelgrabowski** [comment] 2022-12-21 19:18
I did now – uninstalled the existing version first. I had to manually re-add my bridge once afterwards, but I had to do that when switching to the fixed version from alfadormx  as well. Now everything is working fine with 1.6.2 – I did restart the Stream Deck software a few times as well, because in the past that seemed to be a way to trigger the problem – no issue so far. I'll monitor over the coming days, sometimes it would work for a day or two in the past as well and only occur after a few reboots.

**Comment by tiptronic** [comment] 2022-12-21 19:21
thanks @manuelgrabowski for the quick feedback.

Please keep in mind: if you uninstall the plugin using StreamDeck's uninstall, then the settings are removed as well - thus you have to pair again. I will make sure we update the store-plugin more frequently, so you shouldn't need to do the remove/install in the future...

If you find something, please add it to the discussion or create a new issue

**Comment by mstuercke** [comment] 2022-12-23 12:16
I installed the 1.6.2 version and it works quite well incl. restarting Stream Deck. But all bridges are still lost after restarting the computer.
The store says, that the current version is 1.4. Is it possible, that the plugin get's "updated" to the lower version on restarting the computer?

**Comment by tiptronic** [comment] 2022-12-23 13:53
@mstuercke that shouldn't be the case!!!
But anyway, since the feedback we got is quite good, we'll release the latest version a bit later today to the store - which hopefully fixes those problems.
Unfortunately it seems we can't do anything about the 429 Error except what we have now.

If the settings are not retained after a restart of the computer, this most likely means there are some Firewall (or other) blockers which don't allow adding the bridge's properties to the system-settings. In this case we need to take a closer look...

**Comment by mstuercke** [comment] 2022-12-23 14:04
@tiptronic Okay, I'll wait for the release in the store and will give feedback then

**Comment by tiptronic** [comment] 2022-12-23 15:49
it's live on the store now!

**Comment by alfadormx** [comment] 2022-12-28 06:30
I´m glad I could help (even if it was just a tiny bit)

**Comment by tiptronic** [comment] 2022-12-28 10:50
@alfadormx _ANY_ help is appreciated - no matter huge or small!

**Closed by tiptronic** 2022-12-28 10:50 UTC
